version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    # volumes:
    #   - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
