version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./backend/db.sqlite3:/app/backend/db.sqlite3
    env_file:
      - .env
    depends_on:
      - frontend

  frontend:
    image: node:20-slim
    container_name: frontend_dev
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
